import About from "@/components/About";
import Apps from "@/components/Apps";
import BVDLabs from "@/components/BVDLabs";
import Footer from "@/components/Footer";
import Immortalised from "@/components/Immortalised";
import Landing from "@/components/Landing";
import Links from "@/components/Links";
import Navbar from "@/components/Navbar";
// import PartnerSection from '@/components/PartnerSection'
import Partnerships from "@/components/Partnerships";
import Team from "@/components/Team";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>BVDCAT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg">
        <Navbar />
        <Landing />
        <Apps />
        <Partnerships />
        {/* <PartnerSection /> */}
        <About />
        <Links />
        <Immortalised />
        <BVDLabs />
        <Team />
        <Footer />
      </main>
    </>
  );
}
